#! /bin/sh

EMAIL=tim.j.wilkinson@gmail.com

dpkg-scanpackages --multiversion . > Packages
gzip -k Packages

apt-ftparchive release . > Release
gpg --default-key "${EMAIL}" -abs -o - Release > Release.gpg
gpg --default-key "${EMAIL}" --clearsign -o - Release > InRelease

git add -A
git commit -m update
git push
