#! /bin/sh

EMAIL=tim.j.wilkinson@gmail.com
DIST=dev

#dpkg-scanpackages --multiversion ${DIST} > ${DIST}/Packages
#rm -f ${DIST}/Packages.gz
#gzip -k ${DIST}/Packages

echo "Codename: dev/" > ${DIST}/Release
apt-ftparchive release ${DIST} >> ${DIST}/Release
gpg --default-key "${EMAIL}" -abs -o - ${DIST}/Release > ${DIST}/Release.gpg
gpg --default-key "${EMAIL}" --clearsign -o - ${DIST}/Release > ${DIST}/InRelease

#git add -A ${DIST}/*.deb
#git commit -m update
#git push
